### ISSUE TITLE
Error when running deno task cli address

### ISSUE THREAD

**Issue by wafflepool-cardano** [aiken-lang/fortuna#11]
System: Ubuntu 22.04 LTS virtual machine
Running a fully synced cardano-node. Kupo and ogmios running as a service locally.

`deno task cli init ` - worked and created _seed.txt_

`deno task cli address` - yields this error:

`Task cli deno run --allow-all miner/main.ts "address"
error: Top-level await promise never resolved
await new Command()
^
    at <anonymous> (file://fortuna/miner/main.ts:401:1)
`

The `.env` file in fortuna root directory is configured as such (default values for kupo and ogmios):
`KUPO_URL="wss://127.0.0.1"
OGMIOS_URL="wss://127.0.0.1"`

**Comment by caike** [comment]
OGMIOS_URL needs to be prefixed with "http://" and KUPO_URL with "ws://" unless you are actually using a secured connection

**Comment by wafflepool-cardano** [comment]
Thank you for replying. 
`.env` file has been changed to:
`KUPO_URL="ws://127.0.0.1:1442"
OGMIOS_URL="http://127.0.0.1:1337"
`

Now getting this error when running the same command:

`error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'costModels')
          Object.keys(result.costModels).forEach((v) => {
                             ^
    at WebSocket.client.addEventListener.once (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:45:30)
    at innerInvokeEventListeners (ext:deno_web/02_event.js:750:7)
    at invokeEventListeners (ext:deno_web/02_event.js:797:5)
    at dispatch (ext:deno_web/02_event.js:654:9)
    at WebSocket.[[[eventLoop]]] (ext:deno_websocket/01_websocket.js:434:11)
    at eventLoopTick (ext:core/01_core.js:183:11)
`

cardano-node, kupo and ogmios are all running as services in the background.

**Comment by wafflepool-cardano** [comment]
I can `telnet` into kupo and ogmios. Cardano-node connection gets closed after a few seconds, but its a fully functional and synced relay with incoming and outgoing connections.

Kupo is fully synced, with current `slotNo` matching that of `cardano-node query tip`.

Kupo is running with those flags `--since origin --match addr1q9vv07dvhf45w9cx8pcjrseky0azmqg0uh0kkjc3kun3p45pueq3e6tezsa5wzugtmkz4x08xu6pleccdk9g9t9fjfwq0z744r`
The address comes from the seed generated by `deno task cli init`, which I then restored on Eternl wallet. Unsure as to whether that is affecting anything.

**Comment by caike** [comment]
For Kupo you will also need to add tuna's validator address as an additional match, like `--match addr1wynelppvx0hdjp2tnc78pnt28veznqjecf9h3wy4edqajxsg7hwsc`.

Or simply use `--match '*/*'` - I'm personally running it this way and have been able to mint blocks successfully.

**Comment by wafflepool-cardano** [comment]
I'm still struggling with this and stuck at the same step. Do you run ogmios and kupo as a service as well? Would it be possible to know your configurations and see if there's something I missed or did wrong?

**Comment by caike** [comment]
Ogmios

```bash
./bin/ogmios --node-socket ${NODE_SOCKET} \
	--host 0.0.0.0 \
	--node-config ${NODE_CONFIG} \
	--port ${OGMIOS_PORT}
```

Kupo

```bash
./bin/kupo \
	--ogmios-host 127.0.0.1 \
	--ogmios-port ${OGMIOS_PORT} \
	--host 0.0.0.0 \
	--port ${KUPO_PORT} \
	--prune-utxo \
	--since 101511155.b019548e41b55ae702fee37d8b9ae716c978712c02bc4862ba13db6602e5af72 \
	--in-memory \
	--match '*/*' \
	--log-level Info
```
