### ISSUE TITLE
Create wallet

### ISSUE THREAD

**Issue by miyogm** [aiken-lang/fortuna#20]
I am executing the deno task cli init command that creates the wallet and creates the seed.txt but it tells me the following
error: Uncaught (in promise) MissingEnvVarsError: The following variables were defined in the example file but are not present in the environment:
   KUPO_URL, OGMIOS_URL

Make sure to add them to your env file.
     throw new MissingEnvVarsError(

Checking the .env file we see that the parameters are well defined and in the correct root:
  KUPO_URL="xxx"
OGMIOS_URL="xxx"

Could it be that being from Europe won't let me?

thanks :D

**Comment by gmaz98** [comment]
Do you have a .env file, or are you using the .env.example?

**Comment by miyogm** [comment]
I have a file with xxx.env I had also tried it with the one I already had but without success

**Comment by tp3005eth** [comment]
make sure your endpoints start with https:// and wss://. Also name it just ".env" and nothing else

**Comment by gmaz98** [comment]
<img width="954" alt="Captura de Tela 2023-08-30 às 21 50 07" src="https://github.com/aiken-lang/fortuna/assets/113480944/47e64187-551c-45c7-b76a-13cf6760e1a4">

It should look something like this.

**Comment by miyogm** [comment]
![Captura](https://github.com/aiken-lang/fortuna/assets/140986049/af4a864d-674b-418d-b93a-63e8fef20c70)

Identical however with error

**Comment by miyogm** [comment]
Update: I had to modify the name of the example since it was detected as .env
problem solved
