### ISSUE TITLE
Uncaught (in promise) SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by BrockCruess** [aiken-lang/fortuna#22]
```
error: Uncaught (in promise) SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    const result = await fetch(
```

**Comment by caike** [comment]
Might be a connection issue with Ogmios or Kupo. Make you can access them from where you are running your miner and that Kupo is fully synced.

**Comment by BrockCruess** [comment]
> 

I'm using Demeter for now, Kupo claims to be 100% synced and Ogmios doesn't offer much info

**Comment by BrockCruess** [comment]
Trying that Kupo link now, I'll let it run for a bit to see if this specific error keeps happening. Other errors that I've reported are still happening for sure.
After watching the Ogmios monitor for a few minutes it goes to Status: KO (with a skull logo) once in a while for a minute or two, however it doesn't necessarily crash the miner during those times.

**Comment by rvcas** [comment]
the problem is that you are getting a bad response for the services that the lucid provider is using under the hood.
