### ISSUE TITLE
The ADA is not seen reflected

### ISSUE THREAD

**Issue by miyogm** [aiken-lang/fortuna#24]
I have sent about 50 ADA to my wallet, however at the end of all the verifications /30 I do not see it reflected but by searching my wallet if they appear, any solution in this regard? thank you
https://cardanoscan.io/address/addr1q990qc507n0m20d3d8vjk89txv0gcxmznvjz6kqkwj8cpxwvsvsdu87h5838mh8c8d7n2zfm4mv77jv3ktamu3gqxgksnkkmnj

![Captura](https://github.com/aiken-lang/fortuna/assets/140986049/62c91daf-e757-4de2-a289-ce28b2306552)

**Comment by rvcas** [comment]
This is likely due to an issue with your hosted kupo being out of sync. Many people have started running kupo locally. If you were to recover this seed phrase in a trusted wallet you would likely see the correct balance.
