### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'datum')

### ISSUE THREAD

**Issue by BrockCruess** [aiken-lang/fortuna#25]
Nothing changed in any of my files, but suddenly after a few hours of mining I'm getting this repeatedly:

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'datum')
      let validatorState = validatorOutRef.datum!;
```

**Comment by rvcas** [comment]
it's an issue with kupo on demeter most likely, instead of making fixes to this miner a new one is being worked on
