### ISSUE TITLE
Missing input or output for some native asset

### ISSUE THREAD

**Issue by luciantugui** [aiken-lang/fortuna#7]
Found next datum: d8799f190c8b5820000003dd5988c71f9d9126583fdc799c61fa4738753540ff032bbb4aa18d7e6205193fff1a02d3ccf81b0000018a3d7f00804d416c4c204861496c2074556e419f582000000195372fc5d1ac30b2a68a56f754bea8c1e5eeb2092fecb7e42992e2acfd5820000000feedd58e87ee12e224efd631536c3d57aadbb18ec62f44180366a3def858200000005943d4dcb4755ae88d22f32220675f1a272078380bb8cb4c94902e2d1258200000001571546b479ba412dc37f5126ca465f29bdce01514e4b41ed9d3cd1a8558200000001571546b479ba412dc37f5126ca465f29bdce01514e4b41ed9d3cd1a85582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933a582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933a582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933a582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933a582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933affff
Missing input or output for some native asset

**Comment by MicroProofs** [comment]
If you can, I also need the transaction cbor to look into any issues. I can't tell much on just the datum alone

**Comment by btbf** [comment]
I'm getting the same message too.
```
New block not found in 30 seconds, updating state
Found next datum: d8799f190e2758200000028119316ea25a836a65b7a33e380c0dae2180cc6fc25ef6e9c8e3c97a0105193fff1a043871c01b0000018a3ee3a5484d416c4c204861496c2074556e419f58200000019882b150cd20cdb0742642223e7bc1d2be59c581be7031e5addf50e28758200000005e6c844e9ff1c83e2ad84669c15b85d0c028f8a85768b88e173298644858200000005e6c844e9ff1c83e2ad84669c15b85d0c028f8a85768b88e173298644858200000000ae9cbbfc058e8f7b387f5f3ed453b0c30bdca74fe477726b32dfb36e758200000000ae9cbbfc058e8f7b387f5f3ed453b0c30bdca74fe477726b32dfb36e758200000000ae9cbbfc058e8f7b387f5f3ed453b0c30bdca74fe477726b32dfb36e7582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933a582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933a582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933a582000000000b91969a15f0116e0026b2169f5d9859146ca56741af39bb810ac933affff
Missing input or output for some native asset
Mining...
New block not found in 30 seconds, updating state
```


```
~/fortuna$ deno task cli address
Task cli deno run --allow-all miner/main.ts "address"
Address: <mask>
ADA Balance: 0
TUNA Balance: 0
```
I can see the balance in explorer, but deno does not show the balance.

**Comment by btbf** [comment]
The kupo instance selection was able to eliminate this problem by selecting "PRUNE UTXO No".
